# Generated by Django 2.0.2 on 2018-11-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catsndogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Master',
            new_name='CatsDogs',
        ),
    ]
