# Generated by Django 2.0.2 on 2018-12-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='github',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
