# Generated by Django 2.0.2 on 2018-11-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='excelmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('team', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
