# Generated by Django 2.0.2 on 2018-11-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelmodel',
            name='image',
            field=models.FileField(upload_to='files/'),
        ),
    ]
