# Generated by Django 2.0.2 on 2018-11-11 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_auto_20181106_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excelmodel',
            old_name='team',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='excelmodel',
            old_name='image',
            new_name='csv',
        ),
    ]
